spring:
  application:
    name: hello-spring-cloud-zuul
  # 服务追踪
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8769

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

zuul:
  routes:
    # 以 /api/ribbon 开头的请求都转发给 hello-spring-cloud-web-admin-ribbon 服务
    api-ribbon:
      path: /api/ribbon/**
      serviceId: hello-spring-cloud-web-admin-ribbon
    api-feign:
      path: /api/feign/**
      serviceId: hello-spring-cloud-web-admin-feign