stages:
  - build
  - push
  - run
  - clean

# 编译
build:
  stage: build
  script:
  - /usr/local/maven/apache-maven-3.5.3/bin/mvn clean package
  - cp target/itoken-zuul-1.0.0-SNAPSHOT.jar docker
  - cd docker
  - docker build -t 127.0.0.1:5000/itoken-zuul .

# 部署到服务器
push:
  stage: push
  script:
  - docker push 127.0.0.1:5000/itoken-zuul

# 运行
run:
  stage: run
  script:
  - cd docker
  - docker-compose down
  - docker-compose up -d

clean:
  stage: clean
  script:
  - docker rmi $(docker images -q -f dangling=true)