version: '3.1'
services:
  itoken-zuul:
    restart: always
    container_name: itoken-zuul
    image: 127.0.0.1:5000/itoken-zuul
    ports:
      - 8769:8769
    networks:
    - zuul-network

networks:
  zuul-network: