spring:
  application:
    name: hello-spring-cloud-zipkin

server:
  port: 9411

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false
