version: '3.1'
services:
  itoken-zipkin:
    restart: always
    container_name: itoken-zipkin
    image: 127.0.0.1:5000/itoken-zipkin
    ports:
      - 9411:9411
    networks:
    - zipkin-network

networks:
  zipkin-network: