version: '3.1'
services:
  itoken-service-sso:
    restart: always
    container_name: itoken-service-sso
    image: 127.0.0.1:5000/itoken-service-sso
    ports:
      - 8501:8501
    networks:
    - service-sso-network

networks:
  service-sso-network: