spring:
  application:
    name: hello-spring-cloud-web-admin-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  cloud:
    loadbalancer:
      retry:
        enabled: true
  # 服务追踪
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8765

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

# 熔断器配置
feign:
  hystrix:
    enabled: true
