version: '3.1'
services:
  itoken-admin:
    restart: always
    container_name: itoken-admin
    image: 127.0.0.1:5000/itoken-admin
    ports:
      - 8084:8084
    networks:
    - admin-network

networks:
  admin-network: