version: '3.1'
services:
  itoken-service-redis:
    restart: always
    container_name: itoken-service-redis
    image: 127.0.0.1:5000/itoken-service-redis
    ports:
      - 8502:8502
    networks:
    - service-redis-network

networks:
  service-redis-network: